version: 2
updates:
  - package-ecosystem: npm
    directory: 'server/'
    schedule:
      interval: daily
      time: '20:00'
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: 'ui/'
    schedule:
      interval: daily
      time: '20:00'
    open-pull-requests-limit: 10